version: '3'
services:
  hermes:
    image: ghcr.io/ls1intum/hermes:latest
    container_name: hermes
    ports:
      - "17333:8080"
    environment:
      - APNS_CERTIFICATE_PWD
      - APNS_PROD_ENVIRONMENT
      - APNS_CERTIFICATE_PATH=/key/artemis-apns.p12
      - GOOGLE_APPLICATION_CREDENTIALS=/firebase.json
    volumes:
      - ${APNS_CERT_PATH}:/key/artemis-apns.p12
      - ${GOOGLE_APPLICATION_CREDENTIALS_JSON}:/firebase.json
    restart: on-failure
