name: Build and Push Docker

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-push-docker-image:
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main